[phases.install]
cmds = ["COMPOSER_MEMORY_LIMIT=-1 composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --no-scripts"]

[phases.build]
cmds = [
    "mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs storage/app/public",
    "rm -f bootstrap/cache/packages.php bootstrap/cache/services.php"
]

[start]
cmd = "php artisan storage:link --force; php artisan migrate --force; php artisan db:seed --class=AdminSeeder --force; php artisan db:seed --class=SiteStatSeeder --force; php artisan serve --host=0.0.0.0 --port=$PORT"
