[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.pdo_pgsql",
    "php82Extensions.gd",
    "php82Extensions.zip",
    "php82Extensions.exif",
    "php82Extensions.intl",
    "php82Extensions.imagick",
    "imagemagick"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --no-scripts"
]

[phases.build]
cmds = [
    "mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs storage/app/public",
    "rm -f bootstrap/cache/packages.php bootstrap/cache/services.php"
]

[start]
cmd = "php artisan package:discover --ansi; php artisan storage:link --force; php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
